// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz_c0LLLsYE7RAP96FotkttpqNgt1LMo0',
    appId: '1:331426257007:web:e74b78fd7384765a6a159a',
    messagingSenderId: '331426257007',
    projectId: 'prakflutterfirebase-be10e',
    authDomain: 'prakflutterfirebase-be10e.firebaseapp.com',
    databaseURL: 'https://prakflutterfirebase-be10e-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-be10e.appspot.com',
    measurementId: 'G-H4YC324MGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdGZ_tpYzy1gxYVNr9nRQhQ8M3BBEWN7M',
    appId: '1:331426257007:android:2827fad779dc68dd6a159a',
    messagingSenderId: '331426257007',
    projectId: 'prakflutterfirebase-be10e',
    databaseURL: 'https://prakflutterfirebase-be10e-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-be10e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs3W9h6gnnTxJ9QtCV6kSq3J0GUqNRTVw',
    appId: '1:331426257007:ios:ca480e7a8e1e66026a159a',
    messagingSenderId: '331426257007',
    projectId: 'prakflutterfirebase-be10e',
    databaseURL: 'https://prakflutterfirebase-be10e-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-be10e.appspot.com',
    iosClientId: '331426257007-8e5u44qlsgs0rsf2gs5mhjne3j696qr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs3W9h6gnnTxJ9QtCV6kSq3J0GUqNRTVw',
    appId: '1:331426257007:ios:ca480e7a8e1e66026a159a',
    messagingSenderId: '331426257007',
    projectId: 'prakflutterfirebase-be10e',
    databaseURL: 'https://prakflutterfirebase-be10e-default-rtdb.firebaseio.com',
    storageBucket: 'prakflutterfirebase-be10e.appspot.com',
    iosClientId: '331426257007-8e5u44qlsgs0rsf2gs5mhjne3j696qr2.apps.googleusercontent.com',
    iosBundleId: 'com.example.praktikum6',
  );
}
